### ISSUE TITLE
Models Unnecessarily Destroyed and Recreated During Plan and Apply Phases

### ISSUE THREAD

**Issue by jkfran** [Pwd9000-ML/terraform-azurerm-openai-service#52]
**Expected Behavior:**
The expected behavior is that the Terraform plan should recognize the existing state of the OpenAI models and not mark them for destruction and re-creation if there are no changes to the model configurations.

**Actual Behavior:**
During the Terraform plan and apply phases, OpenAI models are being marked for destruction and re-creation, despite no changes to the configuration. The `cognitive_account_id` and `id` attributes are shown as forces replacement, which suggests a possible issue with state recognition or configuration drift.

**Steps to Reproduce:**

It doesn't happens always but the steps are:

1. Write a Terraform configuration that includes an `azurerm_cognitive_deployment` resource.
2. Run `terraform apply` to create the resources.
3. Without making any changes to the configuration, run `terraform plan` or `terraform apply` again.
4. Observe that the resources are marked for replacement despite no changes.

**Comment by Pwd9000-ML** [comment]
@jkfran 
Is the note behavior if you build a new OpenAI Service or use an existing one?
Can you confirm if you are building the Service as part of the model deployment, or just a model deployment on an existing service built already outside of the terraform module.

**Comment by jkfran** [comment]
@Pwd9000-ML It happens from time to time when I perform modifications in the OpenAI deployments. The last time was when a adding a new deployment on a new region. All the previous deployments were destroyed and recreated because of this.

**Comment by Pwd9000-ML** [comment]
@jkfran 
This makes sense and thanks for contributing to a fix
